name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code
      - name: Lint the code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Run Jupyter Notebook tests
      - name: Test Jupyter Notebooks
        run: |
          pip install nbconvert
          for notebook in $(find . -name "*.ipynb"); do
            jupyter nbconvert --to notebook --execute "$notebook" --output test-output.ipynb;
          done

      # Run Pytest (optional)
      - name: Run Pytest
        run: |
          pip install pytest
          pytest
